//
//  NorthHall.swift
//  Thesis-Test
//
//  Created by Brandan Gianni on 8/23/21.
//

import Foundation

let NorthHall = AdjacencyList<String>()

let f612 = NorthHall.createVertex(data: "612")
let f613 = NorthHall.createVertex(data: "613")
let f6endconnect = NorthHall.createVertex(data: "6end")
let f6StairA = NorthHall.createVertex(data: "6_StairA")
let f611 = NorthHall.createVertex(data: "611")
let f610 = NorthHall.createVertex(data: "610")
let f609 = NorthHall.createVertex(data: "609")
let f608 = NorthHall.createVertex(data: "608")
let f607 = NorthHall.createVertex(data: "607")
let f606 = NorthHall.createVertex(data: "606")
let f605 = NorthHall.createVertex(data: "605")
let f6Trash = NorthHall.createVertex(data: "6Trash")
let f6leraconnect = NorthHall.createVertex(data: "6lera")
let f6elevator = NorthHall.createVertex(data: "6_elevator")
let f600 = NorthHall.createVertex(data: "600")
let f601 = NorthHall.createVertex(data: "601")
let f602 = NorthHall.createVertex(data: "602")
let f603 = NorthHall.createVertex(data: "603")
let f604 = NorthHall.createVertex(data: "604")
let f6Laundry = NorthHall.createVertex(data: "6Laundry")
let f6triconnect = NorthHall.createVertex(data: "6tri")
let f6StairB = NorthHall.createVertex(data: "6_StairB")
let f6Lounge = NorthHall.createVertex(data: "6Lounge")

let f512 = NorthHall.createVertex(data: "512")
let f513 = NorthHall.createVertex(data: "513")
let f5endconnect = NorthHall.createVertex(data: "5end")
let f5StairA = NorthHall.createVertex(data: "5_StairA")
let f511 = NorthHall.createVertex(data: "511")
let f510 = NorthHall.createVertex(data: "510")
let f509 = NorthHall.createVertex(data: "509")
let f508 = NorthHall.createVertex(data: "508")
let f507 = NorthHall.createVertex(data: "507")
let f506 = NorthHall.createVertex(data: "506")
let f505 = NorthHall.createVertex(data: "505")
let f5Trash = NorthHall.createVertex(data: "5Trash")
let f5Lounge = NorthHall.createVertex(data: "5Lounge")
let f5leraconnect = NorthHall.createVertex(data: "5lera")
let f5elevator = NorthHall.createVertex(data: "5_elevator")
let f500 = NorthHall.createVertex(data: "500")
let f501 = NorthHall.createVertex(data: "501")
let f502 = NorthHall.createVertex(data: "502")
let f503 = NorthHall.createVertex(data: "503")
let f504 = NorthHall.createVertex(data: "504")
let f5Laundry = NorthHall.createVertex(data: "5Laundry")
let f5triconnect = NorthHall.createVertex(data: "5try")
let f5StairB = NorthHall.createVertex(data: "5_StairB")

let f412 = NorthHall.createVertex(data: "412")
let f413 = NorthHall.createVertex(data: "413")
let f4endconnect = NorthHall.createVertex(data: "4end")
let f4StairA = NorthHall.createVertex(data: "4_StairA")
let f411 = NorthHall.createVertex(data: "411")
let f410 = NorthHall.createVertex(data: "410")
let f409 = NorthHall.createVertex(data: "409")
let f408 = NorthHall.createVertex(data: "408")
let f407 = NorthHall.createVertex(data: "407")
let f406 = NorthHall.createVertex(data: "406")
let f405 = NorthHall.createVertex(data: "405")
let f4Trash = NorthHall.createVertex(data: "4Trash")
let f4leraconnect = NorthHall.createVertex(data: "4lera")
let f4elevator = NorthHall.createVertex(data: "4_elevator")
let f400 = NorthHall.createVertex(data: "400")
let f401 = NorthHall.createVertex(data: "401")
let f402 = NorthHall.createVertex(data: "402")
let f403 = NorthHall.createVertex(data: "403")
let f404 = NorthHall.createVertex(data: "404")
let f4Laundry = NorthHall.createVertex(data: "4Laundry")
let f4triconnect = NorthHall.createVertex(data: "4tri")
let f4StairB = NorthHall.createVertex(data: "4_StairB")
let f4Lounge = NorthHall.createVertex(data: "4Lounge")
let f4Kitchen = NorthHall.createVertex(data: "4Kitchen")

let f312 = NorthHall.createVertex(data: "312")
let f313 = NorthHall.createVertex(data: "313")
let f3endconnect = NorthHall.createVertex(data: "3end")
let f3StairA = NorthHall.createVertex(data: "3_StairA")
let f311 = NorthHall.createVertex(data: "311")
let f310 = NorthHall.createVertex(data: "310")
let f309 = NorthHall.createVertex(data: "309")
let f308 = NorthHall.createVertex(data: "308")
let f307 = NorthHall.createVertex(data: "307")
let f306 = NorthHall.createVertex(data: "306")
let f305 = NorthHall.createVertex(data: "305")
let f3Trash = NorthHall.createVertex(data: "3Trash")
let f3leraconnect = NorthHall.createVertex(data: "3lera")
let f3elevator = NorthHall.createVertex(data: "3_elevator")
let f300 = NorthHall.createVertex(data: "300")
let f301 = NorthHall.createVertex(data: "301")
let f302 = NorthHall.createVertex(data: "302")
let f303 = NorthHall.createVertex(data: "303")
let f304 = NorthHall.createVertex(data: "304")
let f3Laundry = NorthHall.createVertex(data: "3Laundry")
let f3triconnect = NorthHall.createVertex(data: "3tri")
let f3StairB = NorthHall.createVertex(data: "3_StairB")
let f3Lounge = NorthHall.createVertex(data: "3Lounge")

let f212 = NorthHall.createVertex(data: "2212")
let f213 = NorthHall.createVertex(data: "2213")
let f2endconnect = NorthHall.createVertex(data: "2end")
let f2StairA = NorthHall.createVertex(data: "2_StairA")
let f211 = NorthHall.createVertex(data: "211")
let f210 = NorthHall.createVertex(data: "210")
let f209 = NorthHall.createVertex(data: "209")
let f208 = NorthHall.createVertex(data: "208")
let f207 = NorthHall.createVertex(data: "207")
let f206 = NorthHall.createVertex(data: "206")
let f205 = NorthHall.createVertex(data: "205")
let f2Trash = NorthHall.createVertex(data: "2Trash")
let f2leraconnect = NorthHall.createVertex(data: "2lera")
let f2elevator = NorthHall.createVertex(data: "2_elevator")
let f200 = NorthHall.createVertex(data: "200")
let f201 = NorthHall.createVertex(data: "201")
let f202 = NorthHall.createVertex(data: "202")
let f203 = NorthHall.createVertex(data: "203")
let f204 = NorthHall.createVertex(data: "204")
let f2Laundry = NorthHall.createVertex(data: "2Laundry")
let f2triconnect = NorthHall.createVertex(data: "2try")
let f2StairB = NorthHall.createVertex(data: "2_StairB")
let f2Lounge = NorthHall.createVertex(data: "2Lounge")
let f2Kitchen = NorthHall.createVertex(data: "2Kitchen")

let f112 = NorthHall.createVertex(data: "112")
let f113 = NorthHall.createVertex(data: "113")
let f1endconnect = NorthHall.createVertex(data: "1end")
let f1StairA = NorthHall.createVertex(data: "1_StairA")
let f111 = NorthHall.createVertex(data: "111")
let f110 = NorthHall.createVertex(data: "110")
let f109 = NorthHall.createVertex(data: "109")
let f108 = NorthHall.createVertex(data: "108")
let f107 = NorthHall.createVertex(data: "107")
let f106 = NorthHall.createVertex(data: "106")
let f105 = NorthHall.createVertex(data: "105")
let f1Trash = NorthHall.createVertex(data: "1Trash")
let f1leraconnect = NorthHall.createVertex(data: "1lera")
let f1elevator = NorthHall.createVertex(data: "1_elevator")
let f100 = NorthHall.createVertex(data: "100")
let f101 = NorthHall.createVertex(data: "101")
let f102 = NorthHall.createVertex(data: "102")
let f103 = NorthHall.createVertex(data: "103")
let f104 = NorthHall.createVertex(data: "104")
let f1Laundry = NorthHall.createVertex(data: "1Laundry")
let f1triconnect = NorthHall.createVertex(data: "1tri")
let f1StairB = NorthHall.createVertex(data: "1_StairB")
let f1Lounge = NorthHall.createVertex(data: "1Lounge")
let f1StairGround = NorthHall.createVertex(data: "1_Top")

let fLStairGround = NorthHall.createVertex(data: "L_Top")
let fLelevator = NorthHall.createVertex(data: "L_elevator")
let entrance = NorthHall.createVertex(data: "entrance")
let RHD = NorthHall.createVertex(data: "RHD")
let mail = NorthHall.createVertex(data: "mailbox")
let vending = NorthHall.createVertex(data: "vending")
let frontDesk = NorthHall.createVertex(data: "FrontDesk")
let groundconnector = NorthHall.createVertex(data: "groundcenter")

let null = NorthHall.createVertex(data: "null")

